//
//  TripTable.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import UIKit
import AWSDynamoDB

class TripTable: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _tripID: NSNumber?
    var _creationDate: NSNumber?
    var _creatorUserID: String?
    var _destinationCoordinates: Set<NSNumber>?
    var _destinationDate: NSNumber?
    var _destinationLatitude: NSNumber?
    var _destinationLongitude: NSNumber?
    var _destinationName: String?
    var _isDriver: NSNumber?
    var _isMatched: NSNumber?
    var _originCoordinates: Set<NSNumber>?
    var _originDate: NSNumber?
    var _originLatitude: NSNumber?
    var _originLongitude: NSNumber?
    var _originName: String?
    
    class func dynamoDBTableName() -> String {

        return "hitch-mobilehub-1320700761-TripTable"
    }
    
    class func hashKeyAttribute() -> String {

        return "_tripID"
    }
    
    public override static func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_tripID" : "tripID",
               "_creationDate" : "creationDate",
               "_creatorUserID" : "creatorUserID",
               "_destinationCoordinates" : "destinationCoordinates",
               "_destinationDate" : "destinationDate",
               "_destinationLatitude" : "destinationLatitude",
               "_destinationLongitude" : "destinationLongitude",
               "_destinationName" : "destinationName",
               "_isDriver" : "isDriver",
               "_isMatched" : "isMatched",
               "_originCoordinates" : "originCoordinates",
               "_originDate" : "originDate",
               "_originLatitude" : "originLatitude",
               "_originLongitude" : "originLongitude",
               "_originName" : "originName",
        ]
    }
}
