//
//  CloudLogicAPIFactory.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import AWSCore

class CloudLogicAPIFactory {
    static var supportedCloudLogicAPIs: [CloudLogicAPI] {
        
        return [
            CloudLogicAPI(displayName: "functionThree",
                          apiDescription: "",
                          paths: [
                            "/items", "/items/123",                ],
                          endPoint: "https://941zml5ob5.execute-api.us-east-1.amazonaws.com/Development",
                          apiClient: AWSAPI_941ZML5OB5_FunctionThreeMobileHubClient.init(forKey: AWSCloudLogicDefaultConfigurationKey)
            ),
            CloudLogicAPI(displayName: "funcitonTwo",
                          apiDescription: "",
                          paths: [
                            "/items", "/items/123",                ],
                          endPoint: "https://wm412qkrjb.execute-api.us-east-1.amazonaws.com/Development",
                          apiClient: AWSAPI_WM412QKRJB_FuncitonTwoMobileHubClient.init(forKey: AWSCloudLogicDefaultConfigurationKey)
            ),
            CloudLogicAPI(displayName: "riderPolygonFinder-MobileHub-195141552",
                          apiDescription: "",
                          paths: [
                            "/items", "/items/123",                ],
                          endPoint: "https://03rmtzmv63.execute-api.us-east-1.amazonaws.com/Development",
                          apiClient: AWSAPI_03RMTZMV63_RiderPolygonFinderMobileHubClient.init(forKey: AWSCloudLogicDefaultConfigurationKey)
            ),
        ]
    }
}
