//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//
//

import AWSCore

// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-east-1_WTfzpszTx"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "7e529c02lciuiegu56ankf93dl"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .usEast1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "1u2uiaqnqca8pj7moa6a4pnspklpm7nan4g27j9nefbe2va34r57"


// Identifier for Cloud Logic API invocation clients
let AWSCloudLogicDefaultConfigurationKey: String = "CloudLogicAPIKey"
let AWSCloudLogicDefaultRegion: AWSRegionType = .usEast1
